@startuml name "Wichtige Funktionen"
'alt + D um das UML-Diagramm anzuzeigen
'STRG + S ==> Speichern

' abstract
' abstract class
' circle
' interface
' diamond für Raute
' entity

' class ClassName <Dies soll eine Notiz adrstellen>
' class time <<(D,#FF7700)datatype>>
' enum Buchungszustand <<enumeration>>
' class time <<(D,#FF7700)>>

' /AnzahlWartender ist ein abgeleitetes Attribut
' --Durchgestrichener Text--

' +
' -
' # protected
' ~ package privat
' {static} für statische Attribute oder Operationen
' Methode {abstract} : string

header Page Header
footer Page %page% of %lastpage%
title ProgrammierPraktikum Schiffe versenken \nCopyright by Maximilian Stricker, Nandor Csizmadia, Fabian Saur

class Spielfeld
{

}

class BattleShip
{

}

class Benutzer
{

}

abstract abstractNutzer
{

}

class KI 
{

}

abstractNutzer <-down- Benutzer
abstractNutzer <-down- KI

'InterfaceSpielfeld -right- BattleShip
'BattleShip -right- InterfaceNutzer
Spielfeld -right- abstractNutzer


BattleShip -up-> Spielfeld



' package PackageName {
    'Was gehört dazu?
'}


' ggf.  left right up down einfügen
' --|> Extension
' --* Composition
' --o Aggregation

' -->
' ..>
' ..|>
' *-->
' #--
' x--
' }--
' +--
' ^--


' Beziehung1 "Mulitiplizität"    --  "Mulitiplizität" Beziehung1 : BeschreibungPfeil < | >
' WarteListe "0..*" o-- "0..*\n{ordered}\n+Wartender" Kunde 

' <> diamond
' Klasse1 -- diamond

@enduml